# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
game_versions_mr=1.21.5
game_versions_curse=1.21.5
parchment_version=1.21:2024.07.07
loader_version=0.16.10

# Mod Properties
mod_version=1.1.0
maven_group=red.jackf
archives_base_name=granulargamerules

# Dependencies
jackfredlib_version=0.10.7+1.21.5
yacl_version=3.6.6+1.21.5-fabric

# JF_AUTO_UPDATE_BLOCK
fabric-api_version=0.119.5+1.21.5
modmenu_version=14.0.0-rc.1
emi_version=1.1.12+1.21
# JF_END_AUTO_UPDATE_BLOCK

mixinextras_version=0.5.0-beta.5

# Publishing
prefix=[1.21.5]
release_type=beta
changelog_filter=[feat],[fix],[change],[docs],[update]
mod_name=Granular Gamerules
github_owner=JackFred2
github_repo=GranularGamerules
github_url=https://github.com/JackFred2/GranularGamerules

mr_project_id=YFUweSka
cf_project_id=1106224